### ISSUE TITLE
Uncaught (in promise) Http: connection closed before message completed

### ISSUE THREAD

**Issue by erfanium** [cmorten/native_http#4]
# Issue

Setup:

- Deno version: 1.12.2
- v8 version: 9.2.230.14
- Typescript version: 4.3.5

## Details
My code:
```ts
import { listenAndServe } from "https://deno.land/x/native_http@0.3.1/mod.ts";

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

listenAndServe(3003, async (requestEvent) => {
  await delay(2000);
  const body = "Hi";
  requestEvent.respondWith(new Response(body, { status: 200 })).catch((e) => {
    console.error(e);
  });
});

console.log("Listening on port 3003.");
```

Although I have catch that rejection, but I still get uncaught promise errors that kills the process.

to reproduce, I use [autocannon](https://www.npmjs.com/package/autocannon)
```
autocannon localhost:3003 -t=1
```

**Comment by cmorten** [comment]
Hey @erfanium 👋 

Does the error produce a message + stack to the console that you could share to help debug?

**Comment by erfanium** [comment]
Here is my logs
```
Listening on port 3003.
Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
error: Uncaught (in promise) Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)

```

**Comment by erfanium** [comment]
Another logs
```
Listening on port 3003.
Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
error: Uncaught (in promise) Http: connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)

```

**Comment by erfanium** [comment]
```
Listening on port 4505.
error: Uncaught (in promise) Http: connection closed before message completed
      await serverRequest.done;
      ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:183:27)
    at async Server.iterateHttpRequests (file:///home/erfanium/Documents/native_http/server.ts:159:7)
    at async Server.acceptConnAndIterateHttpRequests (file:///home/erfanium/Documents/native_http/server.ts:223:5)
    at async MuxAsyncIterator.callIteratorNext (https://deno.land/std@0.101.0/async/mux_async_iterator.ts:30:31)
```

**Comment by cmorten** [comment]
Ok cool, coming out of the `respondWith` method on the request event

https://github.com/denoland/deno/blob/main/extensions/http/01_http.js#L183

Which will always throw

https://github.com/denoland/deno/blob/main/extensions/http/01_http.js#L197

Curious thing is that the lib returns the `respondWith` promise so would expect your `.catch()` to be handling these errors - can you confirm that your catch isn’t logging these and a separate error is causing the process to exit?

**Comment by cmorten** [comment]
Are thanks, that stack is a bit more detailed and useful ☺️

**Comment by erfanium** [comment]
@cmorten 
Should I create a PR?

**Comment by cmorten** [comment]
@erfanium if you’re happy to then that would be awesome! Should be similar to https://github.com/denoland/deno_std/blob/main/http/server.ts#L186 from std/http where just wrap in a try catch that swallows the error and kills the loop as the connection is dead

**Comment by erfanium** [comment]
@cmorten Great, Thanks! I'm working on it
